# first installation : conda env create --prefix ./env -f environment.yml
# update : mamba env update --prefix ./env -f environment.yml --prune

name: data-examples
channels:
    - defaults
    - conda-forge
dependencies:
    - python=3.10
    - mamba
    - pip
    - pip:
        - jupyter
        - ipykernel
        - matplotlib
        - seaborn
        - numpy
        - pandas
        - scikit-learn
        - tensorflow>=2.11.*